---
dependencies:
  - name: etcd3
  - name: etcd3/facts
  - name: etcd3/backups/cron
    vars:
      skip_initial_backup: true
    when: inventory_hostname in groups[etcd_cluster_group]
    tags:
      - backup-cron
