---
- name: Defragment etcd database
  shell: |
    {{ bin_dir }}/etcdctl \
      --endpoints={{ etcd_clusters[etcd_cluster_name].etcd_access_addresses }} \
      --cert={{ etcd_clusters[etcd_cluster_name].etcd_cert_paths.client.cert }} \
      --key={{ etcd_clusters[etcd_cluster_name].etcd_cert_paths.client.key }} \
      --cacert={{ etcd_clusters[etcd_cluster_name].etcd_cert_paths.client.ca }} \
      defrag
  environment:
    ETCDCTL_API: "3"
  register: defrag_result

- name: Display defrag result
  debug:
    var: defrag_result.stdout_lines
