---
- name: Defragment etcd database
  shell: |
    {{ bin_dir }}/etcdctl \
      --endpoints=$(cat /etc/etcd/etcd-*-conf.yaml | grep advertise-client-urls | cut -d' ' -f2) \
      --cert=/etc/etcd/ssl/etcd-*-client.crt \
      --key=/etc/etcd/ssl/etcd-*-client.key \
      --cacert=/etc/etcd/ssl/root_ca.crt \
      defrag
  environment:
    ETCDCTL_API: "3"
  register: defrag_result

- name: Display defrag result
  debug:
    var: defrag_result.stdout_lines
