---
- name: View etcd logs (use cluster-specific service name)
  command: journalctl -u {{ etcd_clusters[etcd_cluster_name].etcd_name }} -n 50 --no-pager
  register: etcd_logs
  changed_when: false

- name: Display logs
  debug:
    var: etcd_logs.stdout_lines
