---
- name: List cluster members
  shell: |
    {{ bin_dir }}/etcdctl \
      --endpoints=$(cat /etc/etcd/etcd-*-conf.yaml | grep advertise-client-urls | cut -d' ' -f2) \
      --cert=/etc/etcd/ssl/etcd-*-client.crt \
      --key=/etc/etcd/ssl/etcd-*-client.key \
      --cacert=/etc/etcd/ssl/root_ca.crt \
      member list -w table
  environment:
    ETCDCTL_API: "3"
  register: cluster_members
  changed_when: false

- name: Display cluster members
  debug:
    var: cluster_members.stdout_lines
