---
- name: List cluster members
  shell: |
    {{ bin_dir }}/etcdctl \
      --endpoints={{ etcd_clusters[etcd_cluster_name].etcd_access_addresses }} \
      --cert={{ etcd_clusters[etcd_cluster_name].etcd_cert_paths.client.cert }} \
      --key={{ etcd_clusters[etcd_cluster_name].etcd_cert_paths.client.key }} \
      --cacert={{ etcd_clusters[etcd_cluster_name].etcd_cert_paths.client.ca }} \
      member list -w table
  environment:
    ETCDCTL_API: "3"
  register: cluster_members
  changed_when: false

- name: Display cluster members
  debug:
    var: cluster_members.stdout_lines
